[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
